### ISSUE TITLE
API request to leave a group

### ISSUE THREAD

**Issue by leMaik** [Welfenlab/tutor-student#30]
To support leaving a group (for #13), we need an API request to leave the current group (= create a new group with only the user himself and join that group). Should return the new user object.

**Comment by LittleHelicase** [comment]
I think it is sufficient to push an empty array to `/api/group`. This creates a new group with no one else in it.

**Comment by leMaik** [comment]
Throws an internal server error for me (using RethinkDB).

**Comment by leMaik** [comment]
*bump* I get 500 errors whenever I try to create a group. The response is:
```
ReqlDriverError: Cannot wrap undefined with r.expr().<br> &nbsp;at ReqlDriverError.ReqlError (/home/maik/Gits/tutor-meta/tutor-student/node_modules/@tutor/rethinkdb-database/node_modules/rethinkdb/errors.js:14:13)<br> &nbsp;at new ReqlDriverError (/home/maik/Gits/tutor-meta/tutor-student/node_modules/@tutor/rethinkdb-database/node_modules/rethinkdb/errors.js:37:50)<br> &nbsp;at Function.&lt;anonymous&gt; (/home/maik/Gits/tutor-meta/tutor-student/node_modules/@tutor/rethinkdb-database/node_modules/rethinkdb/ast.js:3938:11)<br> &nbsp;at Function.&lt;anonymous&gt; (/home/maik/Gits/tutor-meta/tutor-student/node_modules/@tutor/rethinkdb-database/node_modules/rethinkdb/util.js:43:16)<br> &nbsp;at pseudonymListToIdList (/home/maik/Gits/tutor-meta/tutor-student/node_modules/@tutor/rethinkdb-database/lib/groups.js:59:16)<br> &nbsp;at createGroup (/home/maik/Gits/tutor-meta/tutor-student/node_modules/@tutor/rethinkdb-database/lib/groups.js:82:22)<br> &nbsp;at Object.create [as dataCall] (/home/maik/Gits/tutor-meta/tutor-student/node_modules/@tutor/rethinkdb-database/lib/groups.js:100:14)<br> &nbsp;at /home/maik/Gits/tutor-meta/tutor-student/node_modules/@tutor/server/lib/rest.js:105:38<br> &nbsp;at Layer.handle [as handle_request] (/home/maik/Gits/tutor-meta/tutor-student/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp;at next (/home/maik/Gits/tutor-meta/tutor-student/node_modules/express/lib/router/route.js:131:13)<br> &nbsp;at Route.dispatch (/home/maik/Gits/tutor-meta/tutor-student/node_modules/express/lib/router/route.js:112:3)<br> &nbsp;at Layer.handle [as handle_request] (/home/maik/Gits/tutor-meta/tutor-student/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp;at /home/maik/Gits/tutor-meta/tutor-student/node_modules/express/lib/router/index.js:277:22<br> &nbsp;at Function.process_params (/home/maik/Gits/tutor-meta/tutor-student/node_modules/express/lib/router/index.js:330:12)<br> &nbsp;at next (/home/maik/Gits/tutor-meta/tutor-student/node_modules/express/lib/router/index.js:271:10)<br> &nbsp;at serveStatic (/home/maik/Gits/tutor-meta/tutor-student/node_modules/express/node_modules/serve-static/index.js:74:16)<br> &nbsp;at Layer.handle [as handle_request] (/home/maik/Gits/tutor-meta/tutor-student/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp;at trim_prefix (/home/maik/Gits/tutor-meta/tutor-student/node_modules/express/lib/router/index.js:312:13)<br> &nbsp;at /home/maik/Gits/tutor-meta/tutor-student/node_modules/express/lib/router/index.js:280:7<br> &nbsp;at Function.process_params (/home/maik/Gits/tutor-meta/tutor-student/node_modules/express/lib/router/index.js:330:12)<br> &nbsp;at next (/home/maik/Gits/tutor-meta/tutor-student/node_modules/express/lib/router/index.js:271:10)<br> &nbsp;at logger (/home/maik/Gits/tutor-meta/tutor-student/node_modules/morgan/index.js:144:5)<br> &nbsp;at Layer.handle [as handle_request] (/home/maik/Gits/tutor-meta/tutor-student/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp;at trim_prefix (/home/maik/Gits/tutor-meta/tutor-student/node_modules/express/lib/router/index.js:312:13)<br> &nbsp;at /home/maik/Gits/tutor-meta/tutor-student/node_modules/express/lib/router/index.js:280:7<br> &nbsp;at Function.process_params (/home/maik/Gits/tutor-meta/tutor-student/node_modules/express/lib/router/index.js:330:12)<br> &nbsp;at next (/home/maik/Gits/tutor-meta/tutor-student/node_modules/express/lib/router/index.js:271:10)<br> &nbsp;at /home/maik/Gits/tutor-meta/tutor-student/src/development.js:17:9<br> &nbsp;at Layer.handle [as handle_request] (/home/maik/Gits/tutor-meta/tutor-student/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp;at trim_prefix (/home/maik/Gits/tutor-meta/tutor-student/node_modules/express/lib/router/index.js:312:13)<br> &nbsp;at /home/maik/Gits/tutor-meta/tutor-student/node_modules/express/lib/router/index.js:280:7<br> &nbsp;at Function.process_params (/home/maik/Gits/tutor-meta/tutor-student/node_modules/express/lib/router/index.js:330:12)<br> &nbsp;at next (/home/maik/Gits/tutor-meta/tutor-student/node_modules/express/lib/router/index.js:271:10)<br> &nbsp;at serveStatic (/home/maik/Gits/tutor-meta/tutor-student/node_modules/express/node_modules/serve-static/index.js:74:16)<br> &nbsp;at Layer.handle [as handle_request] (/home/maik/Gits/tutor-meta/tutor-student/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp;at trim_prefix (/home/maik/Gits/tutor-meta/tutor-student/node_modules/express/lib/router/index.js:312:13)<br> &nbsp;at /home/maik/Gits/tutor-meta/tutor-student/node_modules/express/lib/router/index.js:280:7<br> &nbsp;at Function.process_params (/home/maik/Gits/tutor-meta/tutor-student/node_modules/express/lib/router/index.js:330:12)<br> &nbsp;at next (/home/maik/Gits/tutor-meta/tutor-student/node_modules/express/lib/router/index.js:271:10)<br> &nbsp;at /home/maik/Gits/tutor-meta/tutor-student/node_modules/@tutor/dummy-auth/lib/auth.js:55:16<br> &nbsp;at Layer.handle [as handle_request] (/home/maik/Gits/tutor-meta/tutor-student/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp;at trim_prefix (/home/maik/Gits/tutor-meta/tutor-student/node_modules/express/lib/router/index.js:312:13)<br> &nbsp;at /home/maik/Gits/tutor-meta/tutor-student/node_modules/express/lib/router/index.js:280:7<br> &nbsp;at Function.process_params (/home/maik/Gits/tutor-meta/tutor-student/node_modules/express/lib/router/index.js:330:12)<br> &nbsp;at next (/home/maik/Gits/tutor-meta/tutor-student/node_modules/express/lib/router/index.js:271:10)<br> &nbsp;at /home/maik/Gits/tutor-meta/tutor-student/node_modules/@tutor/dummy-auth/node_modules/express-session/index.js:433:7<br> &nbsp;at /home/maik/Gits/tutor-meta/tutor-student/node_modules/@tutor/dummy-auth/node_modules/express-session-rethinkdb/lib/express-session-rethinkdb.js:33:7<br> &nbsp;at tryCatcher (/home/maik/Gits/tutor-meta/tutor-student/node_modules/@tutor/rethinkdb-database/node_modules/rethinkdb/node_modules/bluebird/js/main/util.js:26:23)<br> &nbsp;at Promise._settlePromiseFromHandler (/home/maik/Gits/tutor-meta/tutor-student/node_modules/@tutor/rethinkdb-database/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:507:31)<br> &nbsp;at Promise._settlePromiseAt (/home/maik/Gits/tutor-meta/tutor-student/node_modules/@tutor/rethinkdb-database/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:581:18)<br> &nbsp;at Promise._settlePromises (/home/maik/Gits/tutor-meta/tutor-student/node_modules/@tutor/rethinkdb-database/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:697:14)<br> &nbsp;at Async._drainQueue (/home/maik/Gits/tutor-meta/tutor-student/node_modules/@tutor/rethinkdb-database/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:123:16)<br> &nbsp;at Async._drainQueues (/home/maik/Gits/tutor-meta/tutor-student/node_modules/@tutor/rethinkdb-database/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:133:10)<br> &nbsp;at Immediate.Async.drainQueues [as _onImmediate] (/home/maik/Gits/tutor-meta/tutor-student/node_modules/@tutor/rethinkdb-database/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:15:14)<br> &nbsp;at processImmediate [as _immediateCallback] (timers.js:367:17)<br>
```

**Comment by LittleHelicase** [comment]
`Cannot wrap undefined with r.expr()`

Looks to me as if you are not sending an users array. Maybe we should add a more readable error message ;) .

**Comment by leMaik** [comment]
We should never ever send stacktraces to the user as they may contain sensitive data (paths, internal objects)...

Also, I'm sending undefined, will fix that in a second.

**Comment by fasib** [comment]
stacktraces != more readable errors
In production every error trace should be eaten and a simple 400,500, etc + message should be enough

**Comment by leMaik** [comment]
Yupp, but they might be useful for debugging purposes, that's why I wanted to log them.
